### PR TITLE
.idea removed

### PR DESCRIPTION
**Pull request by ppamorim**
Hi. Would be amazing to remove the ideia and build folder. It's unecessary.
Thanks.

### CODE REVIEW

**Comment by zhanghai** [comment]
I've always been using the default `.gitignore`s generated by Android Studio from its template, which explicitly ignored only `/.idea/workspace.xml` and `/.idea/libraries`.

Since this is the default value, I'm sticking with it.

Can you give me some reference on the reasons for not including these files?

**Comment by ppamorim** [comment]
This files are generated when you build the project and represent some configs for the build, based on your system. We don't need it here.

**Comment by webmaster128** [comment]
In our project we also experienced that the recommended ignores from IDEA do not make a lot of sense. Many files you are told to check in are auto-generated and even if there are no changes, Android Studio does move XML entries up and down like hell which causes a dirty working tree.

So I recommend to consider a merge when this PR is updated.

**Comment by zhanghai** [comment]
Already done.

**Pull request closed without merging**
